In [12]:
import pandas as pd
h_file_path = '../建网结果/h_美国_平均.csv'
h_data = pd.read_csv(h_file_path)
h_data = h_data.drop(h_data.columns[0], axis=1)
h_sorted = h_data.sort_values(by=['Node1', 'Node2', 'weight'])
h_sorted

     Node1 Node2     weight
2001   ABQ   DAL  15.762069
1998   ABQ   HOU  11.742857
1997   ABQ   MCI  16.314815
2000   ABQ   MDW  11.513274
1999   ABQ   OAK   9.198276
...    ...   ...        ...
1925   TUL   HOU  15.089286
1926   TUL   MDW   6.166667
1924   TUL   SLC   3.849057
1989   TUS   MDW   6.983871
2053   WRG   PSG  20.639344

[2082 rows x 3 columns]

In [ ]:
l_file_path = '../建网结果/l_美国_平均.csv'
l_data = pd.read_csv(l_file_path)